import { Component } from '@angular/core';
import { ComicService } from '../../../services/comic/comic.service';
import { Comic } from 'src/app/models/Comic';
import { CartService } from 'src/app/services/cart/cart.service';
import { Order } from 'src/app/models/Order';

@Component({
  selector: 'app-shoping-cart-client',
  templateUrl: './shoping-cart-client.component.html',
  styleUrls: ['./shoping-cart-client.component.scss']
})
export class ShopingCartClientComponent {

  comics: Comic[] = [];
  genres: any[] = [];
  
  subtotal!:number;

  total!:number;
   


  constructor(private comicService: ComicService,private cartService: CartService) {}
  placeOrder() {
    const order: Order = {
      id: 0, // This will likely be generated by the backend
      date: new Date().toISOString(), // Current date and time
      name: 'Some Name', // You need to set this to the customer's name
      comic_isbn: this.comics.map(comic => comic.isbn), // An array of comic ISBNs
      customer_email: 'customer@example.com', // Set this to the customer's email
      comic: this.comics, // An array of comic objects
    };
  
    this.orderService.createOrder(order).subscribe(
      (createdOrder) => {
        console.log('Order created:', createdOrder);
        // Optionally, reset the cart or show a success message to the user.
      },
      (error) => {
        console.error('Error creating order:', error);
        // Handle errors, show an error message, or provide feedback to the user.
      }
    );
  }
  ngOnInit(): void {
    this.getComics();
    this.getGenres();
    this.setSubtotal();
    this.setTotal();
  }

  getComics(): void {
    this.comics = this.cartService.getCartItems();
  }

  getGenres(): void {
    this.comicService.getGenres().subscribe((genres: any) => {
      this.genres = genres;
    });
  }

  deleteShoppingComic(index:number): void{
    this.cartService.removeFromCart(index);
    this.setSubtotal();
    this.setTotal();
  }

  setSubtotal(): void {
    this.subtotal = this.cartService.getSubtotal();

  }

  setTotal() : void {
    this.total = this.subtotal + 6;
    console.log ("total=" + this.total);
  }
}

